spring:
  datasource:
    url: jdbc:h2:mem:cinema
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8080

management:
  server:
    port: 8888
  endpoints:
    web:
      exposure:
        include: health

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    baseUri: http://localhost:${server.port}

logging:
  level:
    com:
      example: DEBUG
